#!/bin/bash -e

# Dynamic environment loading script ( needed for desktop applications )

#-------------------------------------------------------------------
# Loads environment variables use in interactive bash shells
#-------------------------------------------------------------------

DYNENV_USER=$(id -un)
DYNENV_UID=$(cat /etc/passwd | grep "^${DYNENV_USER}" | cut -d ":" -f3)
DYNENV_GID=$(cat /etc/passwd | grep "^${DYNENV_USER}" | cut -d ":" -f4)
DYNENV_HOME=$(homeof "${DYNENV_USER}")

DYNENV_LOC=/run/user/${DYNENV_UID}/env/*

for f in $DYNENV_LOC; do
  env_variable_name="${f##*/}"
  # FIXME: Remove UID check?
  if [ "${env_variable_name}" != "UID" ] && [ "${env_variable_name}" != "!" ]; then
    export "${env_variable_name}"="`cat $f`"
  fi
done

unset DYNENV_USER DYNENV_UID DYNENV_GID DYNENV_HOME

# NOTE: Example usage

# source /scripts/with-dynenv

# echo ${TEST_LONG_VAR}
